gltf2bam.exe .\assets\Shop.glb .\assets\Shop.bam
gltf2bam.exe .\assets\Tony.glb .\assets\Tony_run.bam
gltf2bam.exe .\assets\Bartender1.glb .\assets\bartender.bam
gltf2bam.exe .\assets\Fredi.glb .\assets\quest_guy.bam    
gltf2bam.exe .\assets\Teresa_idle1.glb .\assets\Teresa_idle1.bam
gltf2bam.exe .\assets\Teresa_run.glb .\assets\Teresa_run.bam
gltf2bam.exe .\assets\Bob_Idle.glb .\assets\Bob_Idle.bam
gltf2bam.exe .\assets\Bob_run.glb .\assets\Bob_run.bam
gltf2bam.exe .\assets\Alfred_idle.glb .\assets\Alfred_idle.bam
gltf2bam.exe .\assets\lfred_run.glb .\assets\Alfred_run.bam